import type { Metadata } from "next";
import { Gothic_A1} from "next/font/google";
import Header from "../components/header";
import AuthContextProvider from "@/components/auth";

import "../globals.css";

const inter = Gothic_A1({
  subsets: ["latin"],
  weight: ["200"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Header />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
