import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import Header from "../components/header";
import AuthContextProvider from "@/components/auth";

import "../globals.css";

const inter = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["300"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Today's To Do</title>
        <script 
        src="https://t1.kakaocdn.net/kakao_js_sdk/2.6.0/kakao.min.js" 
        integrity={process.env.NEXT_PUBLIC_INTEGRITY_VALUE} 
        crossOrigin="anonymous"></script>
      </head>
      <body className={inter.className}>
        <AuthContextProvider>
          <Header />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
